image: java:8

stages:
  - build
  - test

before_script:
  - set GRADLE_USER_HOME=$(pwd)/.gradle

build:
  stage: build
  script: .\gradlew assemble

test:
  stage: test
  script:
    - ./gradlew test
 
after_script:
  - echo "End CI"
