version: "3"
services:

  mysqldb:
    image: juliepetrova/mysql
    networks:
      - boulot-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=itsboulot

  boulot-jdbc-container:
    image: juliepetrova/boulot
    ports:
      - "8080:8080"
    networks:
      - boulot-mysql
    depends_on:
      - mysqldb

networks:
  boulot-mysql: