version: '3'

services:
  docker-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=itsboulot
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3307:3306

  app:
    image: julie/boulot-jobfinder
    ports:
       - 8091:8080
    depends_on:
       - docker-mysql